#!perl -s
sub syntax {
	print "Syntax: $0 -dec|-enc <options>
	
	-dec: decode a number with suffix to simple decimal
	-enc: encode a simple decimal to number with suffix
	-n:   don't print units\n";
	exit 0;
}

sub enc {

}

sub dec {
	%pow = ( "K", 1, "k", 1, "M", 2, "G", 3, "T", 4 );
	%conv = ( "dec", 1000, "bin", 1024 );
	while(<>) {
		if ( m/([0-9]*\.?[0-9]*)\s*([KkMGT]?)(i?)([A-Za-z]*)/ ) {
			my ( $num, $bin, $mult );
		       	$bin = ( $3 eq "i" ) ? "bin" : "dec";
			$mult = $2 ? $conv{$bin} ** $pow{$2} : 1;
			$num = $1 * $mult;
			print defined $n ? "$num\n" : "$num $4\n";
		} else {
			print STDERR "Error: invalid number\n";
			exit 1;
		}
	}
}

#syntax if undef $enc and undef $dec
syntax if $h;
enc if $enc;
dec if $dec;
