#!/usr/bin/zsh

# 
# Copyright (C) 2014i, Lorenzo Mureu <mureulor@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this 
# list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without 
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

conv() {
	typeset -F 3 tmp=$1
	typeset -F 3 div
	cnt=1

	if [[ "$2" == "bin" ]]
	then
		(( div = 1024 ))
		suf=( "B" "KiB" "MiB" "GiB" )
	else
		(( div = 1000 ))
		suf=( B KB MB GB )
	fi

	while [[ $cnt -le 4 && $(( $tmp / $div )) -gt 0.1 ]]
	do
		(( tmp = $tmp / $div ))
		(( cnt = $cnt + 1 ))
	done
	echo $tmp ${suf[$cnt]}
}

tot=0
for size in $( pacman -Si "$@" | awk '/Installed Size/{ print $4$5 }' | numsuf -dec -n)
do
	tot=$(( $tot + $size ))
done


	#mult=`echo $size | grep -o '[KMGT]$'`
#	#value=`echo $size | grep -Po '^[[:digit:]]*\.?[[:digit:]]+'`
	
val=$(conv $tot)
echo "Total size is $val."
