#!/usr/bin/env zsh

# 
# Copyright (C) 2014i, Lorenzo Mureu <mureulor@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this 
# list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without 
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

function usage {
	echo "Usage: $0 <program> <regexp>"
	exit 1
}

case $# in
2)
	PROGRAM="$1"
	REGEXP="$2"
	;;
1)	
	PROGRAM="$1"
	REGEXP=""
	;;
*)
	usage
esac

mimeapps="$HOME/.local/share/applications/mimeapps.list"
TMPFILE="`mktemp`"

# vediamo se esiste il file altrimenti crea e inizializza
if [[ -f "${mimeapps}" ]]
then
	cp "${mimeapps}" "${mimeapps}.old"
else
	echo "[Added Associations]\n" > $mimeapps
fi

#backup del mimeapps, lavoreremo sempre su questa copia
cp "${mimeapps}" "${TMPFILE}"

for mimetype in `grep Mime /usr/share/applications/${PROGRAM}.desktop | sed 's/MimeType=//' | xargs -d ';'`
do
	if [[ ! ( "${mimetype}" =~ "${REGEXP}" ) ]]
	then
		continue
	fi

	# cerchiamo se c'è gia una entry di mimetype in 
	echo "`grep -v ${mimetype} ${TMPFILE}`\n${mimetype}=${PROGRAM}.desktop;" > "${TMPFILE}"
	echo "Applying mimetype ${mimetype}..."
done

echo "Are you ok with changes? [ (yes|no), default: yes ] "
read isOK

if [[ ${isOK} != "no" ]]
then
	echo "Writing changes to ${mimeapps}\nLeaving backup at ${mimeapps}.bak"
	mv "${mimeapps}" "${mimeapps}.bak"
	mv "${TMPFILE}" "${mimeapps}"
else
	echo "Not applying any changes but leaving file ${mimeapps}.changes"
	mv "${TMPFILE}" "${mimeapps}.changes"
fi
