#!/usr/bin/zsh

# 
# Copyright (C) 2014i, Lorenzo Mureu <mureulor@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this 
# list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without 
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

help () {
	cat <<- EOF
		This script checks wether there are any programs,
		marked as explicitly installed, which are required by other programs
		and maybe could be marked as-dep (maybe is what the user meant)
	EOF
	exit 1
}

MPATH="/usr/local/mscripts"
source $MPATH/.dohelp


# let's gather a list of all the packages explicitly installed that 
# don't belong to any group
list1=`mktemp`
comm <(pacman -Qenq | sort) <(pacman -Qg|cut -f2 -d' ' | sort) -23 > $list1

# let's find the packages in list1 that are also required by other programs
list=`mktemp`
comm $list1 <(pacman -Qentq | sort) -23 > $list

asdep=`mktemp`
for package in `cat $list`
do
	done="false"
	until [[ $done == "true" ]]
	do
		echo -ne "$package -- Action? [Info|Dep|Skip|List] : "
		read action
		case $action in 
			d|D) echo ${package} >> $asdep; done="true";;
			s|S) done="true" ;;
			l) pacman -Ql $package | grep bin ;;
			*) pacman -Qii $package ;;
		esac
	done
done

# Review selection
echo -n "Do you want to review your selections? [Y/n] "
read choice
[[ $choice != "n" ]] && [[ $choice != "N" ]] && less $asdep

echo -n "Do you want to mark those packages as-dep? [Y/n] "
read choice
{ [[ $choice == "n" ]] || [[ $choice == "N" ]] } && exit 0

sudo pacman -D --asdeps - < $asdep

# removing temp files
rm $list1 $list $asdep
