#!/usr/bin/zsh

# 
# Copyright (C) 2014i, Lorenzo Mureu <mureulor@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this 
# list of conditions and the following disclaimer in the documentation and/or other 
# materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors 
# may be used to endorse or promote products derived from this software without 
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
# OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


help () {
	cat <<- eof
		This script allows the user to review the explicitly installed packages
		and provides a way to delete them
		eof
	exit 0
}

MPATH="/usr/local/mscripts"
source $MPATH/.dohelp 

echo "Will gather a list of all explicitly installed packages, which are available on the repos and which don't belong to any group..."

rem=`mktemp`

for line in $(comm <(pacman -Qentq | sort) <(pacman -Qg | cut -f2 -d' ' | sort) -23)
do
	done="false"
	until [[ $done == "true" ]]
	do
		echo -ne "Package $line\tAction? (Info/Keep/Remove/List binaries) [i]: "
		read action
		case $action in
			k|K) done='true';;
			r|R) echo $line >> $rem ; done='true';;
			l|L) pacman -Ql $line | grep bin ;;
			*) pacman -Qi $line ;; 
		esac
	done
done

echo -ne "Do you want to examinate the list of removals? [Y/n] "
read choice
[[ $choice != n ]] && [[ $choice != N ]] && less $rem

echo -ne "Do you want to remove the selected packages? [y/N] "
read choice
[[ $choice != n ]] && [[ $choice != N ]] && sudo pacman -Rs - < $rem

# removing tempfile
rm $rem
